language: c
os: windows

cache:
  directories:
    - C:/Qt

install:
  - |
    if [ ! -e "C:/Qt/5.12.3" ]; then
      curl -vLO http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe;
      ./qt-unified-windows-x86-online.exe --verbose --script tools/qt-installer-windows.qs;
    fi;
    export CMAKE_PREFIX_PATH="C:/Qt/5.12.3/msvc2017_64";

script:
  - mkdir -p build
  - cd build
  - cmake .. -A x64 -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}"
  - cmake --build . --config Release --target package

deploy:
  provider: releases
  draft: true
  api_key:
    secure: 6ICrjzW21Dgus3YBumBUfrMLRneWNKPRc5hZ0qEOgFKNovbCFy48CAVrsSx+9MVjSncygKklugd3zVXPvk1BUDcxmF1zrk+KZu0/FYKzlOVDCjTVjnzywQOvmZqRQGYwY1zUesW7TjC0RE05FTITL8SElYXt1swn1vVpDiymLBGbRcpPvhpSyGaNwCpoFhUHvXJv0TdfWXHQnOZRimUC0iDiS/G3nF4gjMS/I4548RiNCsVrpkOG5YM86reSfLBlVhjxm9ctgqp07wtAaZTiyGI985XgBnizIK8Rc8dZcaimLImoshSBNqE3+Tg5rm6Fz14QAZvt1tcp4CffGYqz7ZjJ+yHXIL5GcrkVLZWIVKrKAwiUF+ACliHxyFgOUqWGiYiCeWfedWWJLpVLRuWZimtZRRYHvyEL0U+8U17kalR6pMt54BE6m5BopwyNXWk7bbMaGJinOEtvZ0a6qfak/dlohW008vBkXEeG1RS+ndXWPQbhYgebqO4VPvXW8fuFF90mWmK6rtqUjZXVHkfzEKQcJ/jgRrptC1czEChur1XRTy5f7P/X/07dSXMPr4dbdils1iK45oCaPu3VCwliieFQ+RHKwpWwl4l6ZtV5gGV4aqyJumBvsRfbeugU0yVfSVWXkOKcxs5kmH0vEmBBT++wlQT0VoGEXotNWS+MXcg=
  file_glob: true
  file: pkg/*
  skip_cleanup: true
  on:
    tags: true
