language: c
jobs:
  include:
  - os: windows
    env: ARCH=x64
  - os: windows
    env: ARCH=x86
  - os: osx
    env: ARCH=x64

cache:
  directories:
    - C:/Qt
    - /usr/local

install:
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      if [ ! -e "C:/Qt/5.12.6" ]; then
        curl -vLO http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe;
        ./qt-unified-windows-x86-online.exe --verbose --script tools/qt-installer-windows.qs;
      fi;
      if [ "$ARCH" = "x64" ]; then
        export CMAKE_PREFIX_PATH="C:/Qt/5.12.6/msvc2017_64";
        export CMAKE_ARCH=x64;
      else
        export CMAKE_PREFIX_PATH="C:/Qt/5.12.6/msvc2017";
        export CMAKE_ARCH=Win32;
      fi
    fi;
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      if [ ! -e "/usr/local/opt/qt" ]; then
        brew update
        brew install qt5;
      fi;
      export CMAKE_PREFIX_PATH="/usr/local/opt/qt";
    fi;


script:
  - mkdir -p build
  - cd build
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmake .. -A ${CMAKE_ARCH} -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}"; fi
  - cmake --build . --config Release
  - cmake --build . --config Release --target test
  - cmake --build . --config Release --target package

deploy:
  provider: releases
  api_key:
    secure: 6ICrjzW21Dgus3YBumBUfrMLRneWNKPRc5hZ0qEOgFKNovbCFy48CAVrsSx+9MVjSncygKklugd3zVXPvk1BUDcxmF1zrk+KZu0/FYKzlOVDCjTVjnzywQOvmZqRQGYwY1zUesW7TjC0RE05FTITL8SElYXt1swn1vVpDiymLBGbRcpPvhpSyGaNwCpoFhUHvXJv0TdfWXHQnOZRimUC0iDiS/G3nF4gjMS/I4548RiNCsVrpkOG5YM86reSfLBlVhjxm9ctgqp07wtAaZTiyGI985XgBnizIK8Rc8dZcaimLImoshSBNqE3+Tg5rm6Fz14QAZvt1tcp4CffGYqz7ZjJ+yHXIL5GcrkVLZWIVKrKAwiUF+ACliHxyFgOUqWGiYiCeWfedWWJLpVLRuWZimtZRRYHvyEL0U+8U17kalR6pMt54BE6m5BopwyNXWk7bbMaGJinOEtvZ0a6qfak/dlohW008vBkXEeG1RS+ndXWPQbhYgebqO4VPvXW8fuFF90mWmK6rtqUjZXVHkfzEKQcJ/jgRrptC1czEChur1XRTy5f7P/X/07dSXMPr4dbdils1iK45oCaPu3VCwliieFQ+RHKwpWwl4l6ZtV5gGV4aqyJumBvsRfbeugU0yVfSVWXkOKcxs5kmH0vEmBBT++wlQT0VoGEXotNWS+MXcg=
  file_glob: true
  file: pkg/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
