#include <libnin/libnin.h>
#include <libnin/jit/jit.h>

static const SymInstr kInstructions[256] = {
    // 0x00
    { SYM_OP_BRK, SYM_ADDR_IMPL},
    { SYM_OP_ORA, SYM_ADDR_IZX},
    { SYM_OP_STP, SYM_ADDR_IMPL},
    { SYM_OP_SLO, SYM_ADDR_IZX},
    { SYM_OP_NOP, SYM_ADDR_Z},
    { SYM_OP_ORA, SYM_ADDR_Z},
    { SYM_OP_ASL, SYM_ADDR_Z},
    { SYM_OP_SLO, SYM_ADDR_Z},
    { SYM_OP_PHP, SYM_ADDR_IMPL},
    { SYM_OP_ORA, SYM_ADDR_IMM},
    { SYM_OP_ASL, SYM_ADDR_IMPL},
    { SYM_OP_ANC, SYM_ADDR_IMM},
    { SYM_OP_NOP, SYM_ADDR_A},
    { SYM_OP_ORA, SYM_ADDR_A},
    { SYM_OP_ASL, SYM_ADDR_A},
    { SYM_OP_SLO, SYM_ADDR_A},
    { SYM_OP_BPL, SYM_ADDR_REL},
    { SYM_OP_ORA, SYM_ADDR_IZY},
    { SYM_OP_STP, SYM_ADDR_IMM},
    { SYM_OP_SLO, SYM_ADDR_IZY},
    { SYM_OP_NOP, SYM_ADDR_ZX},
    { SYM_OP_ORA, SYM_ADDR_ZX},
    { SYM_OP_ASL, SYM_ADDR_ZX},
    { SYM_OP_SLO, SYM_ADDR_ZX},
    { SYM_OP_CLC, SYM_ADDR_IMPL},
    { SYM_OP_ORA, SYM_ADDR_AY},
    { SYM_OP_NOP, SYM_ADDR_IMPL},
    { SYM_OP_SLO, SYM_ADDR_AY},
    { SYM_OP_NOP, SYM_ADDR_AX},
    { SYM_OP_ORA, SYM_ADDR_AX},
    { SYM_OP_ASL, SYM_ADDR_AX},
    { SYM_OP_SLO, SYM_ADDR_AX},

    // 0x20
    { SYM_OP_JSR, SYM_ADDR_A},
    { SYM_OP_AND, SYM_ADDR_IZX},
    { SYM_OP_STP, SYM_ADDR_IMPL},
    { SYM_OP_RLA, SYM_ADDR_IZX},
    { SYM_OP_BIT, SYM_ADDR_Z},
    { SYM_OP_AND, SYM_ADDR_Z},
    { SYM_OP_ROL, SYM_ADDR_Z},
    { SYM_OP_RLA, SYM_ADDR_Z},
    { SYM_OP_PLP, SYM_ADDR_IMPL},
    { SYM_OP_AND, SYM_ADDR_IMM},
    { SYM_OP_ROL, SYM_ADDR_IMPL},
    { SYM_OP_ANC, SYM_ADDR_IMM},
    { SYM_OP_BIT, SYM_ADDR_A},
    { SYM_OP_AND, SYM_ADDR_A},
    { SYM_OP_ROL, SYM_ADDR_A},
    { SYM_OP_RLA, SYM_ADDR_A},
    { SYM_OP_BMI, SYM_ADDR_REL},
    { SYM_OP_AND, SYM_ADDR_IZY},
    { SYM_OP_STP, SYM_ADDR_IMPL},
    { SYM_OP_RLA, SYM_ADDR_IZY},
    { SYM_OP_NOP, SYM_ADDR_ZX},
    { SYM_OP_AND, SYM_ADDR_ZX},
    { SYM_OP_ROL, SYM_ADDR_ZX},
    { SYM_OP_RLA, SYM_ADDR_ZX},
    { SYM_OP_SEC, SYM_ADDR_IMPL},
    { SYM_OP_AND, SYM_ADDR_AY},
    { SYM_OP_NOP, SYM_ADDR_IMPL},
    { SYM_OP_RLA, SYM_ADDR_AY},
    { SYM_OP_NOP, SYM_ADDR_AX},
    { SYM_OP_AND, SYM_ADDR_AX},
    { SYM_OP_ROL, SYM_ADDR_AX},
    { SYM_OP_RLA, SYM_ADDR_AX},

    // 0x40
    { SYM_OP_RTI, SYM_ADDR_IMPL},
    { SYM_OP_EOR, SYM_ADDR_IZX},
    { SYM_OP_STP, SYM_ADDR_IMPL},
    { SYM_OP_SRE, SYM_ADDR_IZX},
    { SYM_OP_NOP, SYM_ADDR_Z},
    { SYM_OP_EOR, SYM_ADDR_Z},
    { SYM_OP_LSR, SYM_ADDR_Z},
    { SYM_OP_SRE, SYM_ADDR_Z},
    { SYM_OP_PHA, SYM_ADDR_IMPL},
    { SYM_OP_EOR, SYM_ADDR_IMM},
    { SYM_OP_LSR, SYM_ADDR_IMPL},
    { SYM_OP_ALR, SYM_ADDR_IMM},
    { SYM_OP_JMP, SYM_ADDR_A},
    { SYM_OP_EOR, SYM_ADDR_A},
    { SYM_OP_LSR, SYM_ADDR_A},
    { SYM_OP_SRE, SYM_ADDR_A},
    { SYM_OP_BVC, SYM_ADDR_REL},
    { SYM_OP_EOR, SYM_ADDR_IZY},
    { SYM_OP_STP, SYM_ADDR_IMPL},
    { SYM_OP_SRE, SYM_ADDR_IZY},
    { SYM_OP_NOP, SYM_ADDR_ZX},
    { SYM_OP_EOR, SYM_ADDR_ZX},
    { SYM_OP_LSR, SYM_ADDR_ZX},
    { SYM_OP_SRE, SYM_ADDR_ZX},
    { SYM_OP_CLI, SYM_ADDR_IMPL},
    { SYM_OP_EOR, SYM_ADDR_AY},
    { SYM_OP_NOP, SYM_ADDR_IMPL},
    { SYM_OP_SRE, SYM_ADDR_AY},
    { SYM_OP_NOP, SYM_ADDR_AX},
    { SYM_OP_EOR, SYM_ADDR_AX},
    { SYM_OP_LSR, SYM_ADDR_AX},
    { SYM_OP_SRE, SYM_ADDR_AX},

    // 0x60
    { SYM_OP_RTS, SYM_ADDR_IMPL },
    { SYM_OP_ADC, SYM_ADDR_IZX },
    { SYM_OP_STP, SYM_ADDR_IMPL },
    { SYM_OP_RRA, SYM_ADDR_IZX },
    { SYM_OP_NOP, SYM_ADDR_Z },
    { SYM_OP_ADC, SYM_ADDR_Z },
    { SYM_OP_ROR, SYM_ADDR_Z },
    { SYM_OP_RRA, SYM_ADDR_Z },
    { SYM_OP_PLA, SYM_ADDR_IMPL },
    { SYM_OP_ADC, SYM_ADDR_IMM },
    { SYM_OP_ROR, SYM_ADDR_IMPL },
    { SYM_OP_ARR, SYM_ADDR_IMM },
    { SYM_OP_JMP, SYM_ADDR_IJMP },
    { SYM_OP_ADC, SYM_ADDR_A },
    { SYM_OP_ROR, SYM_ADDR_A },
    { SYM_OP_RRA, SYM_ADDR_A },
    { SYM_OP_BVS, SYM_ADDR_REL },
    { SYM_OP_ADC, SYM_ADDR_IZY },
    { SYM_OP_STP, SYM_ADDR_IMPL },
    { SYM_OP_RRA, SYM_ADDR_IZY },
    { SYM_OP_NOP, SYM_ADDR_ZX },
    { SYM_OP_ADC, SYM_ADDR_ZX },
    { SYM_OP_ROR, SYM_ADDR_ZX },
    { SYM_OP_RRA, SYM_ADDR_ZX },
    { SYM_OP_SEI, SYM_ADDR_IMPL },
    { SYM_OP_ADC, SYM_ADDR_AY },
    { SYM_OP_NOP, SYM_ADDR_IMPL },
    { SYM_OP_RRA, SYM_ADDR_AY },
    { SYM_OP_NOP, SYM_ADDR_AX },
    { SYM_OP_ADC, SYM_ADDR_AX },
    { SYM_OP_ROR, SYM_ADDR_AX },
    { SYM_OP_RRA, SYM_ADDR_AX },

    // 0x80
    { SYM_OP_NOP, SYM_ADDR_IMM },
    { SYM_OP_STA, SYM_ADDR_IZX },
    { SYM_OP_NOP, SYM_ADDR_IMM },
    { SYM_OP_SAX, SYM_ADDR_IZX },
    { SYM_OP_STY, SYM_ADDR_Z },
    { SYM_OP_STA, SYM_ADDR_Z },
    { SYM_OP_STX, SYM_ADDR_Z },
    { SYM_OP_SAX, SYM_ADDR_Z },
    { SYM_OP_DEY, SYM_ADDR_IMPL },
    { SYM_OP_NOP, SYM_ADDR_IMM },
    { SYM_OP_TXA, SYM_ADDR_IMPL },
    { SYM_OP_XAA, SYM_ADDR_IMM },
    { SYM_OP_STY, SYM_ADDR_A },
    { SYM_OP_STA, SYM_ADDR_A },
    { SYM_OP_STX, SYM_ADDR_A },
    { SYM_OP_SAX, SYM_ADDR_A },
    { SYM_OP_BCC, SYM_ADDR_REL },
    { SYM_OP_STA, SYM_ADDR_IZY },
    { SYM_OP_STP, SYM_ADDR_IMPL },
    { SYM_OP_AHX, SYM_ADDR_IZY },
    { SYM_OP_STY, SYM_ADDR_ZX },
    { SYM_OP_STA, SYM_ADDR_ZX },
    { SYM_OP_STX, SYM_ADDR_ZY },
    { SYM_OP_SAX, SYM_ADDR_ZY },
    { SYM_OP_TYA, SYM_ADDR_IMPL },
    { SYM_OP_STA, SYM_ADDR_AY },
    { SYM_OP_TXS, SYM_ADDR_IMPL },
    { SYM_OP_TAS, SYM_ADDR_AY },
    { SYM_OP_SHY, SYM_ADDR_AX },
    { SYM_OP_STA, SYM_ADDR_AX },
    { SYM_OP_SHX, SYM_ADDR_AY },
    { SYM_OP_AHX, SYM_ADDR_AY },

    // 0xA0
    { SYM_OP_LDY, SYM_ADDR_IMM },
    { SYM_OP_LDA, SYM_ADDR_IZX },
    { SYM_OP_LDX, SYM_ADDR_IMM },
    { SYM_OP_LAX, SYM_ADDR_IZX },
    { SYM_OP_LDY, SYM_ADDR_Z },
    { SYM_OP_LDA, SYM_ADDR_Z },
    { SYM_OP_LDX, SYM_ADDR_Z },
    { SYM_OP_LAX, SYM_ADDR_Z },
    { SYM_OP_TAY, SYM_ADDR_IMPL },
    { SYM_OP_LDA, SYM_ADDR_IMM },
    { SYM_OP_TAX, SYM_ADDR_IMPL },
    { SYM_OP_LAX, SYM_ADDR_IMM },
    { SYM_OP_LDY, SYM_ADDR_A },
    { SYM_OP_LDA, SYM_ADDR_A },
    { SYM_OP_LDX, SYM_ADDR_A },
    { SYM_OP_LAX, SYM_ADDR_A },
    { SYM_OP_BCS, SYM_ADDR_REL },
    { SYM_OP_LDA, SYM_ADDR_IZY },
    { SYM_OP_STP, SYM_ADDR_IMPL },
    { SYM_OP_LAX, SYM_ADDR_IZY },
    { SYM_OP_LDY, SYM_ADDR_ZX },
    { SYM_OP_LDA, SYM_ADDR_ZX },
    { SYM_OP_LDX, SYM_ADDR_ZY },
    { SYM_OP_LAX, SYM_ADDR_ZY },
    { SYM_OP_CLV, SYM_ADDR_IMPL },
    { SYM_OP_LDA, SYM_ADDR_AY },
    { SYM_OP_TSX, SYM_ADDR_IMPL },
    { SYM_OP_LAS, SYM_ADDR_AY },
    { SYM_OP_LDY, SYM_ADDR_AX },
    { SYM_OP_LDA, SYM_ADDR_AX },
    { SYM_OP_LDX, SYM_ADDR_AY },
    { SYM_OP_LAX, SYM_ADDR_AY },

    // 0xC0
    { SYM_OP_CPY, SYM_ADDR_IMM },
    { SYM_OP_CMP, SYM_ADDR_IZX },
    { SYM_OP_NOP, SYM_ADDR_IMM },
    { SYM_OP_DCP, SYM_ADDR_IZX },
    { SYM_OP_CPY, SYM_ADDR_Z },
    { SYM_OP_CMP, SYM_ADDR_Z },
    { SYM_OP_DEC, SYM_ADDR_Z },
    { SYM_OP_DCP, SYM_ADDR_Z },
    { SYM_OP_INY, SYM_ADDR_IMPL },
    { SYM_OP_CMP, SYM_ADDR_IMM },
    { SYM_OP_DEX, SYM_ADDR_IMPL },
    { SYM_OP_AXS, SYM_ADDR_IMM },
    { SYM_OP_CPY, SYM_ADDR_A },
    { SYM_OP_CMP, SYM_ADDR_A },
    { SYM_OP_DEC, SYM_ADDR_A },
    { SYM_OP_DCP, SYM_ADDR_A },
    { SYM_OP_BNE, SYM_ADDR_REL },
    { SYM_OP_CMP, SYM_ADDR_IZY },
    { SYM_OP_STP, SYM_ADDR_IMPL },
    { SYM_OP_DCP, SYM_ADDR_IZY },
    { SYM_OP_NOP, SYM_ADDR_ZX },
    { SYM_OP_CMP, SYM_ADDR_ZX },
    { SYM_OP_DEC, SYM_ADDR_ZX },
    { SYM_OP_DCP, SYM_ADDR_ZX },
    { SYM_OP_CLD, SYM_ADDR_IMPL },
    { SYM_OP_CMP, SYM_ADDR_AY },
    { SYM_OP_NOP, SYM_ADDR_IMPL },
    { SYM_OP_DCP, SYM_ADDR_AY },
    { SYM_OP_NOP, SYM_ADDR_AX },
    { SYM_OP_CMP, SYM_ADDR_AX },
    { SYM_OP_DEC, SYM_ADDR_AX },
    { SYM_OP_DCP, SYM_ADDR_AX },

    // 0xE0
    { SYM_OP_CPX, SYM_ADDR_IMM },
    { SYM_OP_SBC, SYM_ADDR_IZX },
    { SYM_OP_NOP, SYM_ADDR_IMM },
    { SYM_OP_ISC, SYM_ADDR_IZX },
    { SYM_OP_CPX, SYM_ADDR_Z },
    { SYM_OP_SBC, SYM_ADDR_Z },
    { SYM_OP_INC, SYM_ADDR_Z },
    { SYM_OP_ISC, SYM_ADDR_Z },
    { SYM_OP_INX, SYM_ADDR_IMPL },
    { SYM_OP_SBC, SYM_ADDR_IMM },
    { SYM_OP_NOP, SYM_ADDR_IMPL },
    { SYM_OP_SBC, SYM_ADDR_IMM },
    { SYM_OP_CPX, SYM_ADDR_A },
    { SYM_OP_SBC, SYM_ADDR_A },
    { SYM_OP_INC, SYM_ADDR_A },
    { SYM_OP_ISC, SYM_ADDR_A },
    { SYM_OP_BEQ, SYM_ADDR_REL },
    { SYM_OP_SBC, SYM_ADDR_IZY },
    { SYM_OP_STP, SYM_ADDR_IMPL },
    { SYM_OP_ISC, SYM_ADDR_IZY },
    { SYM_OP_NOP, SYM_ADDR_ZX },
    { SYM_OP_SBC, SYM_ADDR_ZX },
    { SYM_OP_INC, SYM_ADDR_ZX },
    { SYM_OP_ISC, SYM_ADDR_ZX },
    { SYM_OP_SED, SYM_ADDR_IMPL },
    { SYM_OP_SBC, SYM_ADDR_AY },
    { SYM_OP_NOP, SYM_ADDR_IMPL },
    { SYM_OP_ISC, SYM_ADDR_AY },
    { SYM_OP_NOP, SYM_ADDR_AX },
    { SYM_OP_SBC, SYM_ADDR_AX },
    { SYM_OP_INC, SYM_ADDR_AX },
    { SYM_OP_ISC, SYM_ADDR_AX },
};

int ninJitDecodeSym(NinState* state, const SymInstr** sym, uint16_t* addr, uint32_t paddr)
{
    uint8_t opcode;

    opcode = state->prgRom[paddr];
    *sym = kInstructions + opcode;

    switch ((*sym)->addressingMode)
    {
    case SYM_ADDR_IMPL:
        *addr = 0;
        return 1;
    case SYM_ADDR_IMM:
    case SYM_ADDR_Z:
    case SYM_ADDR_ZX:
    case SYM_ADDR_ZY:
    case SYM_ADDR_IZX:
    case SYM_ADDR_IZY:
    case SYM_ADDR_REL:
        *addr = state->prgRom[paddr + 1];
        return 2;
    case SYM_ADDR_A:
    case SYM_ADDR_AX:
    case SYM_ADDR_AY:
    case SYM_ADDR_IJMP:
        *addr = ((uint16_t)state->prgRom[paddr + 1] << 8);
        *addr |= (state->prgRom[paddr + 2]);
        return 3;
    }
}
