name: Nin

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Install Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Checkout
      uses: actions/checkout@v2
    - name: cmake
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cd build && cmake --build . --config Release
    - name: test
      run: cd build && cmake --build . --config Release --target test
    - name: package
      run: cd build && cmake --build . --config Release --target package
