name: Nin

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name:
          - win64
          - win32
          - macos
          - linux
        include:
          - name: win64
            os: windows-2019
            qt_arch: win64_msvc2017_64
            cmake_opts: -A x64
          - name: win32
            os: windows-2019
            qt_arch: win32_msvc2017
            cmake_opts: -A Win32
          - name: macos
            os: macos-latest
            cmake_opts: -DCMAKE_BUILD_TYPE=Release
          - name: linux
            os: ubuntu-16.04
            cmake_opts: -DCMAKE_BUILD_TYPE=Release
    runs-on: ${{ matrix.os }}
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.9
      QT_VERSION: 5.9.9
    steps:
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: Qt-${{ env.QT_VERSION }}-${{ matrix.name }}
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        arch: ${{ matrix.qt_arch }}
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        version: ${{ env.QT_VERSION }}
    - name: Install Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      run: |
        mkdir build
    - name: Build
      run: |
        cmake .. ${{ matrix.cmake_opts }}
        cmake --build . --config Release
      working-directory: ./build
    - name: Test
      run: cmake --build . --config Release --target test
      working-directory: ./build
    - name: Package
      run: |
        cmake --build . --config Release --target package
        cmake -E remove_directory ./pkg/_CPack_Packages
      working-directory: ./build
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.name }}
        path: build/pkg
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download win64
        uses: actions/download-artifact@v1
        with:
          name: win64
          path: pkg
      - name: Download win32
        uses: actions/download-artifact@v1
        with:
          name: win32
          path: pkg
      - name: Download macOS
        uses: actions/download-artifact@v1
        with:
          name: macOS
          path: pkg
      - name: Download linux
        uses: actions/download-artifact@v1
        with:
          name: linux
          path: pkg
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "pkg/*"
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
