name: Nin

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build . --config Release
    - name: test
      run: cmake --build . --config Release --target test
    - name: package
      run: cmake --build . --config Release --target package
