name: Nin

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name:
          - win64
          - win32
          - macos
        include:
          - name: win64
            os: windows-2019
            qt_arch: win64_msvc2017_64
            cmake_opts: -A x64
          - name: win32
            os: windows-2019
            qt_arch: win32_msvc2017
            cmake_opts: -A x86
          - name: macos
            os: macos-latest
            cmake_opts: -DCMAKE_BUILD_TYPE=Release
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        arch: ${{ matrix.qt_arch }}
    - name: Install Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      run: |
        mkdir build
    - name: Build
      run: |
        cmake .. ${{ matrix.cmake_opts }}
        cmake --build . --config Release
      working-directory: ./build
    - name: Test
      run: cmake --build . --config Release --target test
      working-directory: ./build
    - name: Package
      run: cmake --build . --config Release --target package
      working-directory: ./build
