name: Nin

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name:
          - win64
          - win32
          - macos
        include:
          - name: win64
            os: windows-2019
            qt_arch: win64_msvc2017_64
            cmake_opts: -A x64
          - name: win32
            os: windows-2019
            qt_arch: win32_msvc2017
            cmake_opts: -A Win32
          - name: macos
            os: macos-latest
            cmake_opts: -DCMAKE_BUILD_TYPE=Release
    runs-on: ${{ matrix.os }}
    steps:
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: Qt-${{ matrix.name }}
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        arch: ${{ matrix.qt_arch }}
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
    - name: Install Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      run: |
        mkdir build
    - name: Build
      run: |
        cmake .. ${{ matrix.cmake_opts }}
        cmake --build . --config Release
      working-directory: ./build
    - name: Test
      run: cmake --build . --config Release --target test
      working-directory: ./build
    - name: Package
      run: |
        cmake --build . --config Release --target package
        cmake -E remove_directory ./pkg/_CPack_Packages
      working-directory: ./build
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.name }}
        path: build/pkg
  release:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download win64
        uses: actions/download-artifact@v1
        with:
          name: win64
          path: pkg
      - name: Download win32
        uses: actions/download-artifact@v1
        with:
          name: win32
          path: pkg
      - name: Download macOS
        uses: actions/download-artifact@v1
        with:
          name: macOS
          path: pkg
      - name: Release
        run: ls -la pkg
